export type StaffAction =
  | "application.verify"
  | "application.approve.bsm.initial"
  | "application.approve.bsm.final"
  | "application.approve.agm"
  | "application.approve.cfo"
  | "application.approve.md"
  | "product.manage"
  | "inventory.manage"
  | "payment.post"
  | "recovery.authorize"
  | "compliance.audit"
  | "customer_support.manage"
  | "ownership.transfer"
  | "staff_user.create"
  | "staff_user.update";
